### ISSUE TITLE
Getting NullPointerException on back button pressed

### ISSUE THREAD

**Issue by bhavikpangea** [card-io/card.io-Android-SDK#188]
### General information

* SDK/Library version: 5.3.0
* Android Version and Device: ZTE ZMAX PRO with Android 6.0.1

### Issue description

Here is the Stack Trace for this issue. 

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean io.card.payment.OverlayView.isAnimating()' on a null object reference
       at io.card.payment.CardIOActivity.onBackPressed(SourceFile:692)
       at android.app.Activity.onKeyUp(Activity.java:2488)
       at android.view.KeyEvent.dispatch(KeyEvent.java:2665)
       at android.app.Activity.dispatchKeyEvent(Activity.java:2741)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2315)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4152)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4114)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3647)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3700)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3666)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3792)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3674)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3849)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3647)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3700)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3666)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3674)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3647)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3700)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3666)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3825)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3986)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2253)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1874)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1865)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2230)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:138)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by falcon4ever** [comment]
I'm seeing the same problem reported on my app in Crashlytics:

Device:
- ZTE ZMAX PRO (Z981) on Android 6.0.1

Running latest Android Card.io SDK:
- io.card:android-sdk:5.5.1

Stacktrace:
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean io.card.payment.OverlayView.isAnimating()' on a null object reference
       at io.card.payment.CardIOActivity.onBackPressed(CardIOActivity.java:680)
       at android.app.Activity.onKeyUp(Activity.java:2488)
       at android.view.KeyEvent.dispatch(KeyEvent.java:2665)
       at android.app.Activity.dispatchKeyEvent(Activity.java:2741)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2315)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4152)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4114)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3647)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3700)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3666)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3792)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3674)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3849)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3647)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3700)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3666)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3674)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3647)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3700)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3666)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3825)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3986)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2253)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1874)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1865)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2230)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:138)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616`

**Comment by ns-jeeb** [comment]
any fix for the is crash? i am getting same crash
