### ISSUE TITLE
 FATAL EXCEPTION: main Process: io.card.development, PID: 4934  android.os.StrictMode$StrictModeViol

### ISSUE THREAD

**Issue by Xiongxiangwei** [card-io/card.io-Android-SDK#224]
### General information

* SDK/Library version: 
* Android Version and Device:

**Comment by Xiongxiangwei** [comment]
03-14 09:35:30.154 4934-4934/io.card.development E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: io.card.development, PID: 4934
                                                                   android.os.StrictMode$StrictModeViolation: policy=327711 violation=2
                                                                       at android.os.StrictMode.executeDeathPenalty(StrictMode.java:1520)
                                                                       at android.os.StrictMode.access$1300(StrictMode.java:126)
                                                                       at android.os.StrictMode$AndroidBlockGuardPolicy.handleViolation(StrictMode.java:1513)
                                                                       at android.os.StrictMode$AndroidBlockGuardPolicy$1.run(StrictMode.java:1395)
                                                                       at android.os.Handler.handleCallback(Handler.java:815)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                       at android.os.Looper.loop(Looper.java:207)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5811)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)
