### ISSUE TITLE
Card scanner view not initiating on nexus device

### ISSUE THREAD

**Issue by Nagendhiran** [card-io/card.io-Android-SDK#57]
I see the following traces when I tried to click on the scan button from the cordova application. I'm using the android studio 1.1.0 version with android gradle plugin of 1.1.2. No proguard enabled on this build.

Device - Nexus 4 - Android 5.0.1 

Can someone please guide me what exactly am i missing in integrating this sdk with my cordova application.?

Trace:

04-13 13:23:36.148  21081-21081/com.sample.cardscanner D/CordovaWebViewClient﹕ onPageFinished(file:///android_asset/www/index.html)
04-13 13:23:36.148  21081-21081/com.sample.cardscanner D/CordovaActivity﹕ onMessage(onPageFinished,file:///android_asset/www/index.html)
04-13 13:23:36.153  21081-21081/com.sample.cardscanner D/CordovaLog﹕ file:///android_asset/www/js/index.js: Line 47 : Received Event: deviceready
04-13 13:23:36.153  21081-21081/com.sample.cardscanner I/chromium﹕ [INFO:CONSOLE(47)] "Received Event: deviceready", source: file:///android_asset/www/js/index.js (47)
04-13 13:23:36.158  21081-21133/com.sample.cardscanner I/card.io﹕ Checking hardware support...
04-13 13:23:36.159  21081-21133/com.sample.cardscanner I/card.io﹕ card.io 5.0.0 03/10/2015 11:22:54 -0500
04-13 13:23:36.162  21081-21133/com.sample.cardscanner D/card.io﹕ Loaded card.io decider library.  nUseNeon():true,nUseTegra():false
04-13 13:23:36.163  21081-21133/com.sample.cardscanner W/linker﹕ libopencv_core.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
04-13 13:23:36.166  21081-21133/com.sample.cardscanner D/card.io﹕ Loaded opencv core library
04-13 13:23:36.167  21081-21133/com.sample.cardscanner W/linker﹕ libopencv_imgproc.so has text relocations. This is wasting memory and prevents security hardening. Please fix.
04-13 13:23:36.169  21081-21133/com.sample.cardscanner D/card.io﹕ Loaded opencv imgproc library
04-13 13:23:36.175  21081-21133/com.sample.cardscanner I/card.io﹕ Loaded card.io NEON library
04-13 13:23:36.512  21081-21133/com.sample.cardscanner W/PluginManager﹕ THREAD WARNING: exec() call to CardIO.canScan blocked the main thread for 358ms. Plugin should use CordovaInterface.getThreadPool().
04-13 13:23:36.520  21081-21081/com.sample.cardscanner D/CordovaLog﹕ file:///android_asset/www/js/index.js: Line 75 : card.io canScan? true
04-13 13:23:36.520  21081-21081/com.sample.cardscanner I/chromium﹕ [INFO:CONSOLE(75)] "card.io canScan? true", source: file:///android_asset/www/js/index.js (75)
04-13 13:23:51.141  21081-21133/com.sample.cardscanner W/System.err﹕ org.json.JSONException: No value for expiry
04-13 13:23:51.141  21081-21133/com.sample.cardscanner W/System.err﹕ at org.json.JSONObject.get(JSONObject.java:389)
04-13 13:23:51.141  21081-21133/com.sample.cardscanner W/System.err﹕ at org.json.JSONObject.getBoolean(JSONObject.java:410)
04-13 13:23:51.141  21081-21133/com.sample.cardscanner W/System.err﹕ at com.keepe.plugins.cardio.CardIO.execute(CardIO.java:45)
04-13 13:23:51.141  21081-21133/com.sample.cardscanner W/System.err﹕ at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:84)
04-13 13:23:51.141  21081-21133/com.sample.cardscanner W/System.err﹕ at org.apache.cordova.PluginManager.exec(PluginManager.java:151)
04-13 13:23:51.141  21081-21133/com.sample.cardscanner W/System.err﹕ at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:63)
04-13 13:23:51.141  21081-21133/com.sample.cardscanner W/System.err﹕ at org.apache.cordova.ExposedJsApi.exec(ExposedJsApi.java:40)
04-13 13:23:51.141  21081-21133/com.sample.cardscanner W/System.err﹕ at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
04-13 13:23:51.141  21081-21133/com.sample.cardscanner W/System.err﹕ at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
04-13 13:23:51.141  21081-21133/com.sample.cardscanner W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
04-13 13:23:51.142  21081-21133/com.sample.cardscanner W/System.err﹕ at android.os.Looper.loop(Looper.java:135)
04-13 13:23:51.142  21081-21133/com.sample.cardscanner W/System.err﹕ at android.os.HandlerThread.run(HandlerThread.java:61)
04-13 13:23:51.142  21081-21133/com.sample.cardscanner W/CordovaPlugin﹕ Attempted to send a second callback for ID: CardIO505903422
    Result was: "Invalid action"
04-13 13:23:51.152  21081-21081/com.sample.cardscanner D/CordovaLog﹕ file:///android_asset/www/js/index.js: Line 71 : card.io scan cancelled
04-13 13:23:51.152  21081-21081/com.sample.cardscanner I/chromium﹕ [INFO:CONSOLE(71)] "card.io scan cancelled", source: file:///android_asset/www/js/index

**Comment by Nagendhiran** [comment]
Its completely a misunderstanding from my end and raised this as bug. I had used wrong options "collect-expiry" (old one) in CardIO.Scan(), which leads this stack trace.  After replacing the proper options, I was able to initiate the card scan view and collect the card information. As its not at all an issue, I'm closing this with simple explanation.

Proper options need to be used as follows
{
            "expiry": true,
            "cvv": true,
            "zip": true,
            "suppressManual": false,
            "suppressConfirm": false,
            "hideLogo": true
 }
