### ISSUE TITLE
Samsung S4 Android 4.4.2 java.lang.NoSuchMethodError: no method with name='onEdgeUpdate'

### ISSUE THREAD

**Issue by n-belokopytov** [card-io/card.io-Android-SDK#68]
W/ApplicationPackageManager﹕ getCSCPackageItemText()
I/CardIOActivity﹕ onCreate() ================================================================
I/I18nManager﹕ Checking locale ar
I/I18nManager﹕ Checking locale da
I/I18nManager﹕ Checking locale de
I/I18nManager﹕ Checking locale en
I/I18nManager﹕ Checking locale en_AU
I/I18nManager﹕ Checking locale en_GB
I/I18nManager﹕ Checking locale es
I/I18nManager﹕ Checking locale es_MX
I/I18nManager﹕ Checking locale fr
I/I18nManager﹕ Checking locale he
I/I18nManager﹕ Checking locale is
I/I18nManager﹕ Checking locale it
I/I18nManager﹕ Checking locale ja
I/I18nManager﹕ Checking locale ko
I/I18nManager﹕ Checking locale ms
I/I18nManager﹕ Checking locale nb
I/I18nManager﹕ Checking locale nl
I/I18nManager﹕ Checking locale pl
I/I18nManager﹕ Checking locale pt
I/I18nManager﹕ Checking locale pt_BR
I/I18nManager﹕ Checking locale ru
I/I18nManager﹕ Checking locale sv
I/I18nManager﹕ Checking locale th
I/I18nManager﹕ Checking locale tr
I/I18nManager﹕ Checking locale zh-Hans
I/I18nManager﹕ Checking locale zh-Hant
I/I18nManager﹕ Checking locale zh-Hant_TW
D/I18nManager﹕ setLanguage(null)
D/I18nManager﹕ null not found.  Attempting to look for en_US
D/I18nManager﹕ setting locale to:en
D/I18nManager﹕ setLanguage(null)
D/I18nManager﹕ null not found.  Attempting to look for en_US
D/I18nManager﹕ setting locale to:en
I/card.io﹕ Checking hardware support...
I/card.io﹕ card.io 5.0.0 03/10/2015 11:22:54 -0500
D/dalvikvm﹕ Trying to load lib /data/app-lib/com.mytest.android-8/libcardioDecider.so 0x42a04c18
D/dalvikvm﹕ Added shared lib /data/app-lib/com.mytest.android-8/libcardioDecider.so 0x42a04c18
D/card.io﹕ Loaded card.io decider library.  nUseNeon():true,nUseTegra():false
D/dalvikvm﹕ Trying to load lib /data/app-lib/com.mytest.android-8/libopencv_core.so 0x42a04c18
W/linker﹕ libopencv_core.so has text relocations. This is wasting memory and is a security risk. Please fix.
D/dalvikvm﹕ Added shared lib /data/app-lib/com.mytest.android-8/libopencv_core.so 0x42a04c18
D/dalvikvm﹕ No JNI_OnLoad found in /data/app-lib/com.mytest.android-8/libopencv_core.so 0x42a04c18, skipping init
D/card.io﹕ Loaded opencv core library
D/dalvikvm﹕ Trying to load lib /data/app-lib/com.mytest.android-8/libopencv_imgproc.so 0x42a04c18
W/linker﹕ libopencv_imgproc.so has text relocations. This is wasting memory and is a security risk. Please fix.
D/dalvikvm﹕ Added shared lib /data/app-lib/com.mytest.android-8/libopencv_imgproc.so 0x42a04c18
D/dalvikvm﹕ No JNI_OnLoad found in /data/app-lib/com.mytest.android-8/libopencv_imgproc.so 0x42a04c18, skipping init
D/card.io﹕ Loaded opencv imgproc library
D/dalvikvm﹕ Trying to load lib /data/app-lib/com.mytest.android-8/libcardioRecognizer.so 0x42a04c18
D/dalvikvm﹕ Added shared lib /data/app-lib/com.mytest.android-8/libcardioRecognizer.so 0x42a04c18
W/dalvikvm﹕ Exception Ljava/lang/NoSuchMethodError; thrown while initializing Lio/card/payment/CardScanner;
D/AndroidRuntime﹕ Shutting down VM
W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41820da0)
D/HockeyApp﹕ Writing unhandled exception to: /data/data/com.mytest.android/files/bb964061-22e0-4dd5-85f2-d9bd0ba295e8.stacktrace
E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.mytest.android, PID: 26251
    java.lang.NoSuchMethodError: no method with name='onEdgeUpdate' signature='(Lio/card/payment/DetectionInfo;)V' in class Lio/card/payment/CardScanner;
            at java.lang.Runtime.nativeLoad(Native Method)
            at java.lang.Runtime.doLoad(Runtime.java:435)
            at java.lang.Runtime.loadLibrary(Runtime.java:363)
            at java.lang.System.loadLibrary(System.java:526)
            at io.card.payment.CardScanner.<clinit>(CardScanner.java:128)
            at io.card.payment.Util.hardwareSupportCheck(Util.java:81)
            at io.card.payment.Util.hardwareSupported(Util.java:66)
            at io.card.payment.CardIOActivity.onCreate(CardIOActivity.java:346)
            at android.app.Activity.performCreate(Activity.java:5426)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2363)
            at android.app.ActivityThread.access$900(ActivityThread.java:161)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5356)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)

Hey guys, so here's what happened - the sample app is working correctly, but when copy-pasted into another app it crashes every time on startActivityForResult with this stacktrace. Is it something that you could investigate?

**Comment by n-belokopytov** [comment]
Proguard rules were loaded from another file, which cut out all the native stuff. No need to investigate further - my bad.

**Comment by fredsabuni** [comment]
sasdasd
